name: Rust

on:
  push:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Cargo Semver Update
      id: update
      uses: lemonxah/cargo_semver_update_and_tag@v1.0.3
      with:
        GITHUB_TOKEN: ${{ github.token }}
    - name: publish crates
      uses: katyo/publish-crates@v1
      with:
        # Cargo registry token
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
